version: '3'

services:
###> doctrine/doctrine-bundle ###
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
            - bedroomMusicMania_app
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
    networks:
            - bedroomMusicMania_app
  php:
        build:
            context: .docker/php
        volumes:
            - ./:/var/www/bedroomMusicMania:cached
            - symfony_app_var:/var/www/bedroomMusicMania/var
            - symfony_app_vendor:/var/www/bedroomMusicMania/vendor
        ports:
            - 8000:8000
        networks:
            - bedroomMusicMania_app

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
    networks:
            - bedroomMusicMania_app
volumes:
    symfony_app_var:
    symfony_app_vendor:
    database_data:


networks:
    bedroomMusicMania_app:

###> doctrine/doctrine-bundle ###
    database_data:
###< doctrine/doctrine-bundle ###
